---
title: "Codebook for Getting and Cleaning Data Course Project"
author: "Rebecca Kee"
output: md_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## CodeBook for *Getting and Cleaning Data Course Project* 
*** 
This codebook describes in detail the dataset used in this project, its variables, as well as the transformations applied to produce a tidy dataset, titled `tidy_data.csv` located in the same directory.   

### Background information on the original dataset
The raw dataset used in this project was obtained from the [Human Activity Recognition Using Smartphones Data Set](http://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones), which contains data collected from the accelerometers from the Samsung Galaxy S smartphone. Specifically, the data is described as follows:   
> The experiments have been carried out with a group of 30 volunteers within an age bracket of 19-48 years. Each person performed six activities (WALKING, WALKING_UPSTAIRS, WALKING_DOWNSTAIRS, SITTING, STANDING, LAYING) wearing a smartphone (Samsung Galaxy S II) on the waist. Using its embedded accelerometer and gyroscope, we captured 3-axial linear acceleration and 3-axial angular velocity at a constant rate of 50Hz. The experiments have been video-recorded to label the data manually. The obtained dataset has been randomly partitioned into two sets, where 70% of the volunteers was selected for generating the training data and 30% the test data.   

> The sensor signals (accelerometer and gyroscope) were pre-processed by applying noise filters and then sampled in fixed-width sliding windows of 2.56 sec and 50% overlap (128 readings/window). The sensor acceleration signal, which has gravitational and body motion components, was separated using a Butterworth low-pass filter into body acceleration and gravity. The gravitational force is assumed to have only low frequency components, therefore a filter with 0.3 Hz cutoff frequency was used. From each window, a vector of features was obtained by calculating variables from the time and frequency domain.

### Tidy data

The original dataset was cleaned to produce a tidy dataset, `tidy_data.csv`.   
It contains a header row with variable names, while the following rows contain the values of these variables. Each row contains the mean of 79 signal measurements, for each subject and activity. Variables are described in detail below.   

### Variables
* `subject` -- an integer from 1 to 30 that identifies the subject  
* `activity` -- a factor with 6 levels:   
  + `WALKING` -- indicates subject was walking  
  + `WALKING_UPSTAIRS` -- indicates subject was walking upstairs  
  + `WALKING_DOWNSTAIRS` -- indicates subject was walking downstairs  
  + `SITTING` -- indicates subject was sitting  
  + `STANDING` -- indicates subject was standing  
  + `LAYING` -- indicates subject was laying  
* `timeBodyAccelerometerMeanX`	
* `timeBodyAccelerometerMeanY`	
* `timeBodyAccelerometerMeanZ`
* `timeBodyAccelerometerStandardDeviationX`	
* `timeBodyAccelerometerStandardDeviationY`	
* `timeBodyAccelerometerStandardDeviationZ`	
* `timeGravityAccelerometerMeanX`
* `timeGravityAccelerometerMeanY`
* `timeGravityAccelerometerMeanZ`
* `timeGravityAccelerometerStandardDeviationX`
* `timeGravityAccelerometerStandardDeviationY`
* `timeGravityAccelerometerStandardDeviationZ`
* `timeBodyAccelerometerJerkMeanX`
* `timeBodyAccelerometerJerkMeanY`
* `timeBodyAccelerometerJerkMeanZ`
* `timeBodyAccelerometerJerkStandardDeviationX`
* `timeBodyAccelerometerJerkStandardDeviationY`
* `timeBodyAccelerometerJerkStandardDeviationZ`
* `timeBodyGyroscopeMeanX`
* `timeBodyGyroscopeMeanY`
* `timeBodyGyroscopeMeanZ`
* `timeBodyGyroscopeStandardDeviationX`
* `timeBodyGyroscopeStandardDeviationY`
* `timeBodyGyroscopeStandardDeviationZ`
* `timeBodyGyroscopeJerkMeanX`
* `timeBodyGyroscopeJerkMeanY`
* `timeBodyGyroscopeJerkMeanZ`
* `timeBodyGyroscopeJerkStandardDeviationX`
* `timeBodyGyroscopeJerkStandardDeviationY`
* `timeBodyGyroscopeJerkStandardDeviationZ`
* `timeBodyAccelerometerMagnitudeMean`
* `timeBodyAccelerometerMagnitudeStandardDeviation`
* `timeGravityAccelerometerMagnitudeMean`
* `timeGravityAccelerometerMagnitudeStandardDeviation`
* `timeBodyAccelerometerJerkMagnitudeMean`
* `timeBodyAccelerometerJerkMagnitudeStandardDeviation`
* `timeBodyGyroscopeMagnitudeMean`
* `timeBodyGyroscopeMagnitudeStandardDeviation`
* `timeBodyGyroscopeJerkMagnitudeMean`
* `timeBodyGyroscopeJerkMagnitudeStandardDeviation`
* `frequencyBodyAccelerometerMeanX`
* `frequencyBodyAccelerometerMeanY`
* `frequencyBodyAccelerometerMeanZ`
* `frequencyBodyAccelerometerStandardDeviationX`
* `frequencyBodyAccelerometerStandardDeviationY`
* `frequencyBodyAccelerometerStandardDeviationZ`
* `frequencyBodyAccelerometerMeanFrequencyX`
* `frequencyBodyAccelerometerMeanFrequencyY`
* `frequencyBodyAccelerometerMeanFrequencyZ`
* `frequencyBodyAccelerometerJerkMeanX`
* `frequencyBodyAccelerometerJerkMeanY`
* `frequencyBodyAccelerometerJerkMeanZ`
* `frequencyBodyAccelerometerJerkStandardDeviationX`
* `frequencyBodyAccelerometerJerkStandardDeviationY`
* `frequencyBodyAccelerometerJerkStandardDeviationZ`
* `frequencyBodyAccelerometerJerkMeanFrequencyX`
* `frequencyBodyAccelerometerJerkMeanFrequencyY`
* `frequencyBodyAccelerometerJerkMeanFrequencyZ`
* `frequencyBodyGyroscopeMeanX`
* `frequencyBodyGyroscopeMeanY`
* `frequencyBodyGyroscopeMeanZ`
* `frequencyBodyGyroscopeStandardDeviationX`
* `frequencyBodyGyroscopeStandardDeviationY`
* `frequencyBodyGyroscopeStandardDeviationZ`
* `frequencyBodyGyroscopeMeanFrequencyX`
* `frequencyBodyGyroscopeMeanFrequencyY`
* `frequencyBodyGyroscopeMeanFrequencyZ`
* `frequencyBodyAccelerometerMagnitudeMean`
* `frequencyBodyAccelerometerMagnitudeStandardDeviation`
* `frequencyBodyAccelerometerMagnitudeMeanFrequency`
* `frequencyBodyAccelerometerJerkMagnitudeMean`
* `frequencyBodyAccelerometerJerkMagnitudeStandardDeviation`
* `frequencyBodyAccelerometerJerkMagnitudeMeanFrequency`
* `frequencyBodyGyroscopeMagnitudeMean`
* `frequencyBodyGyroscopeMagnitudeStandardDeviation`
* `frequencyBodyGyroscopeMagnitudeMeanFrequency`
* `frequencyBodyGyroscopeJerkMagnitudeMean`
* `frequencyBodyGyroscopeJerkMagnitudeStandardDeviation`
* `frequencyBodyGyroscopeJerkMagnitudeMeanFrequency`







